### ISSUE TITLE
Support for gRNAs with a range of efficiency

### ISSUE THREAD

**Issue by dapluggg** [daklab/tiger#1]
Hi, 

I really liked your publication in Nature Biotechnology. Kudos! 

I was wondering if the tiger.py module has/will have support for generating gRNAs of a wide spectrum of efficiencies. For example, I would like 10 guides to my target mRNA that have a normalized logFC score of -3.0, -2.75, -2.5, -2.25. -2.0, ..., -1.0

I understand that this can be done by changing "NUM_TOP_GUIDES = 10" to some larger number and writing a function to filter. I am happy to do it in my fork, just thought it would be a useful addition! Looking forward to testing these guides.

**Comment by astirn** [comment]
Sorry for the delay, for some reason I have not been getting notification of open issues since I transferred the project to my lab's github organization. Let me make some updates and then I will respond in the next day or so.

**Comment by astirn** [comment]
The [website](https://huggingface.co/spaces/Knowles-Lab/tiger) actually does support this now. You have two strategies:

1. Titration by tiling in which you select "All on-target guides per transcript" and cherry pick those with a range of values.
2. Titration by mismatch in which you select "Top 10 guides per transcript & their titration candidates," which will return all 69 (3 nt x 23 guide length) single mismatch candidates for each of the top 10 guides.

Unfortunately, this public version of the repository is a bit behind that which is on the website. I plan to have that fixed by week's end and will update you here.

**Comment by astirn** [comment]
Please reopen issue if you need help.

**Comment by dapluggg** [comment]
Amazing, thank you!

**Comment by astirn** [comment]
I will have the public repository updated to include this code in the coming week in case you want to run things locally. Thanks again for your interest!

**Comment by dapluggg** [comment]
Sounds great! I made a similar script to do this myself. Will be good to compare my results with yours.

**Comment by astirn** [comment]
This repository and the hugging_face sub-module have both been updated to v2.0. hugging_face/tiger.py will contain my titration code. Thanks again for your interest!
