### ISSUE TITLE
Code to achieve Guide Score

### ISSUE THREAD

**Issue by JunxiFeng** [daklab/tiger#5]
Hi Andrew,

Sorry to bother you again! I noticed that on the website, the gRNAs are predicted with a score from 0-1, is it possible that you can share with me the implementation for the transformation? or is it already somewhere in the modules? Thank you so so much!!!!!

Best,
Junxi

**Comment by astirn** [comment]
Hey Junxi,

Earlier, I mentioned that the website is ahead of the github repository.
This difference is because I have a private version of this code where I
develop new features/research ideas. I should have things all synced up
this week or early next week at the latest. Thanks for your patience!

Andrew

**Comment by JunxiFeng** [comment]
Hi Andrew,

I see! Thank you so much!!

Best,
Junxi

**Comment by astirn** [comment]
Will be available tomorrow. Sorry for the delay.

**Comment by astirn** [comment]
Hey Junxi. Thanks for your patience. I just updated the hugging face tool and this repository to version 2.0. I am not using actual GitHub versioning for now, just tags. The guide scoring code can be found in this repository's tiger_trainer.py. I am closing out this final issue. Let me know if anything else comes up. Thanks again for your interest.
