### ISSUE TITLE
Returning gRNAs of length 28

### ISSUE THREAD

**Issue by JunxiFeng** [daklab/tiger#6]
Hi Andrew, 

I noticed that the gRNAs returned by TIGER are of length 23, and after reading the code, it seems that I could change the length of the returned gRNA directly. So I was wondering if it's ok to modify directly and will doing so affect the model performance? Thank you!

**Comment by astirn** [comment]
The TIGER model is trained on data using gRNAs of length 23. Unless you
have data for gRNAs of different lengths and are looking to retrain your
own TIGER variant, do not change the length.

**Comment by astirn** [comment]
The TIGER model is trained on data using gRNAs of length 23. Unless you have data for gRNAs of different lengths and are looking to retrain your own TIGER variant, do NOT change the length.

If you want to use gRNAs of length 28 for your application, I believe you can take the length 23 gRNAs returned by TIGER and append the five additional nucleotides that are the reverse complement of the transcript sequence. That said, I can't remember which direction you extend them (5p vs 3p)--let me ask a biologist and get back to you unless you know the answer.

**Comment by JunxiFeng** [comment]
I see! Thank you Andrew! Also, would it be possible to input user-defined gRNAs and return the scores for these gRNAs only rather than requiring the transcripts and returning either all gRNAs or top 10 scores? I have several gRNAs that I want the scores for, but every time I would need to input the transcripts and get the results for all gRNAs or top 10 (which might not contain the gRNA I am interested in). Thank you so much!!

**Comment by astirn** [comment]
It is possible, but will take a bit of work on your end. The current model uses 
```
CONTEXT_5P = 3
CONTEXT_3P = 0
```
as defined in `hugging_face/tiger.py`, meaning gRNA predictions require target site sequence context. Therefore, you could create a FASTA file for each gRNA of interest. However, instead of putting gRNA sequence in the FASTA file, you will need to put in the targeted transcript sequence (length 23) and include 3 additional nucleotides of 5-prime sequence for a total of length of 26. Does that make sense?

**Comment by JunxiFeng** [comment]
I see! That makes sense! Thank you so much!
